// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKorhyqr8zXKAfeZP-CnrrBNfv22Q3LI0',
    appId: '1:647765502431:android:2c9695fd20ee7cc5133c6a',
    messagingSenderId: '647765502431',
    projectId: 'litra-1e77c',
    databaseURL: 'https://litra-1e77c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'litra-1e77c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHy1Bs5NqYkXhcbxBrmQnw-4-AEe4zR0A',
    appId: '1:647765502431:ios:f39ed78fdc0eab5a133c6a',
    messagingSenderId: '647765502431',
    projectId: 'litra-1e77c',
    databaseURL: 'https://litra-1e77c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'litra-1e77c.firebasestorage.app',
    iosBundleId: 'com.example.litra',
  );

}